quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=tksforge
quarkus.datasource.password=tksforge
quarkus.datasource.jdbc=postgresql://localhost:5432/tksforge
quarkus.hibernate-orm.database.generation=drop-and-create